-- Initial database creation script
-- This is auto-generated by EF Core migrations

CREATE TABLE IF NOT EXISTS `AppSettings` (
    `SettingKey` TEXT NOT NULL,
    `SettingValue` TEXT,
    `LastUpdated` TEXT NOT NULL,
    PRIMARY KEY (`SettingKey`)
);

CREATE TABLE IF NOT EXISTS `Products` (
    `ProductId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `Category` TEXT NOT NULL,
    `ReferenceCode` TEXT NOT NULL UNIQUE,
    `ProductName` TEXT NOT NULL,
    `Specifications` TEXT,
    `Price` TEXT NOT NULL,
    `StockStatus` INTEGER NOT NULL,
    `Vendor` TEXT,
    `LastUpdated` TEXT NOT NULL
);

CREATE INDEX `IX_Products_Category` ON `Products` (`Category`);

CREATE TABLE IF NOT EXISTS `Estimations` (
    `EstimationId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `EstimationNumber` TEXT NOT NULL UNIQUE,
    `ClientName` TEXT NOT NULL,
    `CreatedDate` TEXT NOT NULL,
    `Notes` TEXT,
    `SubTotal` TEXT NOT NULL,
    `ShippingCost` TEXT NOT NULL,
    `Margin` TEXT NOT NULL,
    `Tax` TEXT NOT NULL,
    `TotalPrice` TEXT NOT NULL,
    `Status` TEXT NOT NULL
);

CREATE INDEX `IX_Estimations_CreatedDate` ON `Estimations` (`CreatedDate`);
CREATE INDEX `IX_Estimations_Status` ON `Estimations` (`Status`);

CREATE TABLE IF NOT EXISTS `EstimationDetails` (
    `DetailId` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `EstimationId` INTEGER NOT NULL,
    `ProductId` INTEGER NOT NULL,
    `Quantity` INTEGER NOT NULL,
    `UnitPrice` TEXT NOT NULL,
    `LineTotalPrice` TEXT NOT NULL,
    CONSTRAINT `FK_EstimationDetails_Estimations_EstimationId` FOREIGN KEY (`EstimationId`) REFERENCES `Estimations` (`EstimationId`) ON DELETE CASCADE,
    CONSTRAINT `FK_EstimationDetails_Products_ProductId` FOREIGN KEY (`ProductId`) REFERENCES `Products` (`ProductId`) ON DELETE RESTRICT
);

-- Insert default settings
INSERT OR IGNORE INTO `AppSettings` VALUES ('DefaultMarginPercent', '25', datetime('now'));
INSERT OR IGNORE INTO `AppSettings` VALUES ('DefaultTaxPercent', '11', datetime('now'));
INSERT OR IGNORE INTO `AppSettings` VALUES ('CompanyName', 'PT Electrical Supplies', datetime('now'));
INSERT OR IGNORE INTO `AppSettings` VALUES ('DefaultShippingCost', '50000', datetime('now'));
INSERT OR IGNORE INTO `AppSettings` VALUES ('CurrencySymbol', 'Rp', datetime('now'));
INSERT OR IGNORE INTO `AppSettings` VALUES ('CompanyAddress', 'Jakarta, Indonesia', datetime('now'));
INSERT OR IGNORE INTO `AppSettings` VALUES ('CompanyPhone', '+62-21-xxxx-xxxx', datetime('now'));
