using System.Buffers.Binary;
using System.Text;
using System.Text.Json;
using NSec.Cryptography;

namespace RabKit.Branding;

/// <summary>
/// Loads + verifies a signed <see cref="EditionManifest"/> bundle.
///
/// <para>
/// Bundle layout (single binary blob, embedded as
/// <c>edition.manifest.bundle</c> in the brand pack assembly):
/// <list type="bullet">
///   <item>4 bytes big-endian: length N of the JSON payload</item>
///   <item>N bytes UTF-8 JSON: the <see cref="EditionManifest"/> record</item>
///   <item>64 bytes: Ed25519 detached signature over the N JSON bytes</item>
/// </list>
/// </para>
///
/// <para>
/// Why a binary wrapper instead of plain JSON with an inline signature
/// field? Two reasons:
/// <list type="number">
///   <item>Deterministic — JSON canonicalisation is famously underspecified
///         (key order, number formatting, whitespace). A binary wrapper
///         signs the EXACT bytes that ship, no canonicalisation needed.</item>
///   <item>Compact — 4 bytes + JSON + 64 bytes = no base64 bloat for the
///         signature, no escaping inside the JSON.</item>
/// </list>
/// </para>
///
/// <para>
/// Generated by <c>Tools/sign-edition-manifest.ps1</c> (which invokes
/// <c>dotnet run --project Tools/LicenseKeyGen -- sign-manifest ...</c>).
/// </para>
/// </summary>
public static class SignedManifestLoader
{
    /// <summary>Length of an Ed25519 detached signature in bytes.</summary>
    public const int Ed25519SignatureLength = 64;

    /// <summary>
    /// Verifies <paramref name="signatureBytes"/> against
    /// <paramref name="manifestBytes"/> using <paramref name="publicKeyBase64"/>,
    /// then deserialises the manifest JSON.
    /// </summary>
    /// <param name="manifestBytes">UTF-8 JSON payload bytes.</param>
    /// <param name="signatureBytes">Ed25519 detached signature (64 bytes).</param>
    /// <param name="publicKeyBase64">Expected signer pubkey, base64-encoded raw 32 bytes.</param>
    /// <exception cref="InvalidManifestException">
    /// Thrown when the signature fails to verify, the public key is malformed,
    /// or the JSON cannot be deserialised into a complete manifest.
    /// </exception>
    public static EditionManifest LoadAndVerify(
        byte[] manifestBytes, byte[] signatureBytes, string publicKeyBase64)
    {
        if (manifestBytes == null) throw new ArgumentNullException(nameof(manifestBytes));
        if (signatureBytes == null) throw new ArgumentNullException(nameof(signatureBytes));
        if (string.IsNullOrWhiteSpace(publicKeyBase64))
            throw new ArgumentException("publicKeyBase64 is empty", nameof(publicKeyBase64));

        if (signatureBytes.Length != Ed25519SignatureLength)
            throw new InvalidManifestException(
                $"Signature must be {Ed25519SignatureLength} bytes, got {signatureBytes.Length}.");

        if (manifestBytes.Length == 0)
            throw new InvalidManifestException("Manifest payload is empty.");

        // ── Verify Ed25519 signature ───────────────────────────────────
        PublicKey publicKey;
        try
        {
            var pkBytes = Convert.FromBase64String(publicKeyBase64);
            publicKey = PublicKey.Import(
                SignatureAlgorithm.Ed25519, pkBytes, KeyBlobFormat.RawPublicKey);
        }
        catch (Exception ex)
        {
            throw new InvalidManifestException(
                $"Manifest issuer public key is invalid base64 or wrong length: {ex.Message}", ex);
        }

        bool sigOk = SignatureAlgorithm.Ed25519.Verify(publicKey, manifestBytes, signatureBytes);
        if (!sigOk)
            throw new InvalidManifestException(
                "Manifest signature does not verify with the configured issuer public key. " +
                "The manifest was tampered with, signed by a different issuer, or paired " +
                "with the wrong key.");

        // ── Deserialise JSON ───────────────────────────────────────────
        EditionManifest? manifest;
        try
        {
            manifest = JsonSerializer.Deserialize<EditionManifest>(
                manifestBytes, JsonOptions);
        }
        catch (JsonException ex)
        {
            throw new InvalidManifestException(
                $"Manifest JSON is malformed: {ex.Message}", ex);
        }

        if (manifest == null)
            throw new InvalidManifestException("Manifest deserialised to null.");

        if (string.IsNullOrWhiteSpace(manifest.EditionId))
            throw new InvalidManifestException("Manifest editionId is missing or empty.");
        if (string.IsNullOrWhiteSpace(manifest.EditionTier))
            throw new InvalidManifestException("Manifest editionTier is missing or empty.");
        if (string.IsNullOrWhiteSpace(manifest.Industry))
            throw new InvalidManifestException("Manifest industry is missing or empty.");
        if (manifest.Features == null)
            throw new InvalidManifestException("Manifest features section is missing.");
        if (string.IsNullOrWhiteSpace(manifest.IssuerKey))
            throw new InvalidManifestException("Manifest issuerKey is missing or empty.");

        return manifest;
    }

    /// <summary>
    /// Convenience wrapper: unpacks the [length][json][signature] bundle
    /// layout, then delegates to <see cref="LoadAndVerify"/>.
    /// </summary>
    /// <param name="manifestResourceBytes">The bundle blob (see class doc for layout).</param>
    /// <param name="publicKeyBase64">Expected signer pubkey.</param>
    public static EditionManifest LoadAndVerifyFromBundle(
        byte[] manifestResourceBytes, string publicKeyBase64)
    {
        if (manifestResourceBytes == null)
            throw new ArgumentNullException(nameof(manifestResourceBytes));

        const int minSize = 4 + 1 + Ed25519SignatureLength;  // 4-byte length + ≥1 byte JSON + sig
        if (manifestResourceBytes.Length < minSize)
            throw new InvalidManifestException(
                $"Manifest bundle truncated: need at least {minSize} bytes, got {manifestResourceBytes.Length}.");

        // First 4 bytes: big-endian JSON length
        int jsonLen = BinaryPrimitives.ReadInt32BigEndian(
            new ReadOnlySpan<byte>(manifestResourceBytes, 0, 4));
        if (jsonLen <= 0)
            throw new InvalidManifestException(
                $"Manifest bundle declares non-positive JSON length: {jsonLen}.");

        int expectedTotal = 4 + jsonLen + Ed25519SignatureLength;
        if (manifestResourceBytes.Length != expectedTotal)
            throw new InvalidManifestException(
                $"Manifest bundle size mismatch: header says {jsonLen} JSON bytes " +
                $"(total expected {expectedTotal}), but bundle is {manifestResourceBytes.Length} bytes.");

        var jsonBytes = new byte[jsonLen];
        Buffer.BlockCopy(manifestResourceBytes, 4, jsonBytes, 0, jsonLen);

        var sigBytes = new byte[Ed25519SignatureLength];
        Buffer.BlockCopy(manifestResourceBytes, 4 + jsonLen, sigBytes, 0, Ed25519SignatureLength);

        return LoadAndVerify(jsonBytes, sigBytes, publicKeyBase64);
    }

    /// <summary>
    /// Builds the bundle bytes from a manifest+signature pair. Lives here
    /// so the signing tool and the loader share the exact layout in one
    /// place — no chance of header endianness drift.
    /// </summary>
    public static byte[] PackBundle(byte[] manifestJsonBytes, byte[] signatureBytes)
    {
        if (manifestJsonBytes == null) throw new ArgumentNullException(nameof(manifestJsonBytes));
        if (signatureBytes == null) throw new ArgumentNullException(nameof(signatureBytes));
        if (signatureBytes.Length != Ed25519SignatureLength)
            throw new ArgumentException(
                $"Signature must be {Ed25519SignatureLength} bytes", nameof(signatureBytes));

        var bundle = new byte[4 + manifestJsonBytes.Length + Ed25519SignatureLength];
        BinaryPrimitives.WriteInt32BigEndian(
            new Span<byte>(bundle, 0, 4), manifestJsonBytes.Length);
        Buffer.BlockCopy(manifestJsonBytes, 0, bundle, 4, manifestJsonBytes.Length);
        Buffer.BlockCopy(signatureBytes, 0, bundle, 4 + manifestJsonBytes.Length,
            Ed25519SignatureLength);
        return bundle;
    }

    /// <summary>
    /// Shared <see cref="JsonSerializerOptions"/> for manifest JSON.
    /// Indented output + relaxed case so manually-edited input files still
    /// parse during signing, but emitted bytes from the signer are stable.
    /// Read-only — mutating these at runtime would invalidate signatures.
    /// </summary>
    public static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
        PropertyNameCaseInsensitive = true,
    };

    /// <summary>
    /// Helper for the signing tool — serialise a manifest record to the
    /// canonical UTF-8 bytes that get signed. Single source of truth for
    /// the JSON formatting used at signing time.
    /// </summary>
    public static byte[] SerializeManifestForSigning(EditionManifest manifest)
    {
        if (manifest == null) throw new ArgumentNullException(nameof(manifest));
        var json = JsonSerializer.Serialize(manifest, JsonOptions);
        return Encoding.UTF8.GetBytes(json);
    }
}
